dist: bionic
language: bash
git:
  depth: false
env:
  - COQC=coqc
install:
  - sudo add-apt-repository ppa:jgross-h/coq-8.11-daily -y
  - sudo apt-get update -y
  - sudo apt-get install coq -y
script:
  - make ci
